### PR TITLE
Dropping legacy `app.verbose()` and `app.warn()`.

### LINKED ISSUE #7: `app.verbose()` is being dropped in Sphinx 2.0
The line https://github.com/theacodes/sphinx-docstring-typing/blob/2aea0faecf82a825b5b203a28c81eb87063f533a/sphinx_docstring_typing/__init__.py#L152 results in "scary" warnings, e.g.

```
.../site-packages/sphinx/application.py:413: RemovedInSphinx20Warning: app.verbose() is now deprecated. Use sphinx.util.logging instead.
  RemovedInSphinx20Warning)
```

Seems like the fix is to "Use `sphinx.util.logging` instead"?

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #7.

### CODE REVIEW

**Review by theacodes — APPROVED** [review]

**Comment by dhermes** [comment]
@theacodes Shall we cut a release?

**Comment by theacodes** [comment]
Yes.

**Comment by dhermes** [comment]
Is there any way I can help in cutting said release?

**Comment by theacodes** [comment]
I released it. :)

**Comment by dhermes** [comment]
w00t! Thanks. Just used it and confirmed it works

**Pull request merged**
